group:

  # Swift packages
  - files:
      - source: .gitignore
        dest: .gitignore
      - source: .swiftlint.yml
        dest: .swiftlint.yml
      - source: LICENSE
        dest: LICENSE
      - source: github/
        dest: .github/
        deleteOrphaned: true
    repos: |
      Nef10/SwiftBeanCountImporter
      Nef10/SwiftBeanCountParser
      Nef10/SwiftBeanCountModel
      Nef10/FileSelectorView
      Nef10/SwiftBeanCountWealthsimpleMapper
      Nef10/WealthsimpleDownloader
      Nef10/SwiftBeanCountSheetSync
      Nef10/GoogleAuthentication
      Nef10/RogersBankDownloader
      Nef10/SwiftBeanCountRogersBankMapper

  # Other repos just to sync the license
  - files:
      - source: LICENSE
        dest: LICENSE
        deleteOrphaned: true
    repos: |
      Nef10/SwiftBeanCount
      Nef10/swiftlint-config
