group:
  repos: |
    Nef10/SwiftBeanCountImporter
  files:
    - source: .gitignore
      dest: .gitignore
    - source: .swiftlint.yml
      dest: .swiftlint.yml
    - source: LICENSE
      dest: LICENSE
    - source: github/
      dest: .github/
      deleteOrphaned: true
