group:

  # Swift packages
  - files:
      - source: .gitignore
        dest: .gitignore
      - source: .swiftlint.yml
        dest: .swiftlint.yml
      - source: LICENSE
        dest: LICENSE
      - source: github/
        dest: .github/
        deleteOrphaned: true
        exclude: |
          minimum_coverage.txt
          macos_version.txt
          macos_only
    repos: |
      Nef10/SwiftBeanCountImporter
      Nef10/SwiftBeanCountParser
      Nef10/SwiftBeanCountModel
      Nef10/FileSelectorView
      Nef10/SwiftBeanCountWealthsimpleMapper
      Nef10/WealthsimpleDownloader
      Nef10/SwiftBeanCountSheetSync
      Nef10/GoogleAuthentication
      Nef10/RogersBankDownloader
      Nef10/SwiftBeanCountRogersBankMapper
      Nef10/SwiftBeanCountParserUtils
      Nef10/TangerineDownloader
      Nef10/SwiftBeanCountTangerineMapper
      Nef10/CompassCardDownloader
      Nef10/SwiftBeanCountCompassCardMapper
      Nef10/SwiftBeanCountTax
      
  # Swift package forks (excluding license)
  - files:
      - source: .gitignore
        dest: .gitignore
      - source: .swiftlint.yml
        dest: .swiftlint.yml
      - source: github/
        dest: .github/
        deleteOrphaned: true
        exclude: |
          minimum_coverage.txt
          macos_version.txt
          macos_only
    repos: |
      Nef10/SwiftScraper

  # Swift CLI, excludes the documentation workflow
  - files:
      - source: .gitignore
        dest: .gitignore
      - source: .swiftlint.yml
        dest: .swiftlint.yml
      - source: LICENSE
        dest: LICENSE
      - source: github/
        dest: .github/
        deleteOrphaned: true
        exclude: |
          workflows/docs.yml
          minimum_coverage.txt
          macos_version.txt
          macos_only
    repos: |
      Nef10/SwiftBeanCountCLI
      Nef10/swift-dependency-updater

  # Swift Apps, only sync certain workflows
  - files:
      - source: .gitignore
        dest: .gitignore
      - source: .swiftlint.yml
        dest: .swiftlint.yml
      - source: LICENSE
        dest: LICENSE
      - source: github/labels.yml
        dest: .github/labels.yml
      - source: github/dependabot.yml
        dest: .github/dependabot.yml
      - source: github/release-drafter.yml
        dest: .github/release-drafter.yml
      - source: github/workflows/label-sync.yml
        dest: .github/workflows/label-sync.yml
      - source: github/workflows/release-drafter.yml
        dest: .github/workflows/release-drafter.yml
    repos: |
      Nef10/SwiftBeanCountImporterApp
      Nef10/SwiftBeanCountApp

  # Other repos just to sync the license
  - files:
      - source: LICENSE
        dest: LICENSE
    repos: |
      Nef10/SwiftBeanCount
      Nef10/swiftlint-config
